### ISSUE TITLE
没有网络的时候直接崩溃掉了

### ISSUE THREAD

**Issue by hwp2009** [HoloXia/WanAndroid#1]
可以再优化优化
![image](https://user-images.githubusercontent.com/49135023/172776640-53583957-f63c-45cc-98dc-6f5a1c89aa1a.png)

**Comment by hwp2009** [comment]
![image](https://user-images.githubusercontent.com/49135023/172778586-4128e346-454f-4d6b-a21e-72cfe391bd09.png)
这样搞的话也不合适

**Comment by hwp2009** [comment]
还是直接在这里修改为好呢？
![image](https://user-images.githubusercontent.com/49135023/172782466-b00aeca3-8153-48a9-bfbc-9b4021d8a760.png)

**Comment by HoloXia** [comment]
😄 感谢，目前已经修改。后面有空了再把本地数据库缓存加上~
